[package]
name = "rusty-leveldb-arc"
version = "2.0.0"
authors = ["Lewin Bormann <lbo@spheniscida.de>", "KunoiSayami <i@leanhe.dev>"]
description = "A compatible re-implementation of LevelDB in Rust (But use Arc instead of Rc)"
homepage = "https://github.com/dermesser/leveldb-rs"
repository = "https://github.com/dermesser/leveldb-rs"
readme = "README.md"
keywords = ["LevelDB", "key-value", "database", "SSTable", "Google"]
license = "MIT"
publish = true
edition = "2018"
include = ["src/**/*", "src/*", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
crc = "1.8"
integer-encoding = "3.0"
rand = "0.7"
snap = "1.0"
errno = "0.2"
fs2 = "0.4.3"

tokio = { optional = true, features = ["rt", "sync"], version = ">= 1.21" }

[features]
default = []
async = ["tokio"]

[dev-dependencies]
time-test = "0.2"
bencher = "0.1"

[[bench]]
name = "maps_bench"
harness = false
path = "src/benches/maps_bench.rs"

[workspace]
members = [
    "examples/write-a-lot",
    "examples/leveldb-tool",
    "examples/word-analyze",
    "examples/stresstest",
    "examples/asyncdb",
    "examples/mcpe",
]
